import json
import time

import requests

users = [
    "CGTNOfficial",
    "XHNews",
    "PDChina",
    "ChinaDaily",
    "SpokespersonCHN",
    "ChinaScience",
    "PDChinaLife",
    "zlj517",
    "globaltimesnews",
    "XinhuaChinese",
    "chinaorgcn",
    "PDChinaSports",
    "CGTNFrancais",
    "PDChinese",
    "PDChinaBusiness",
    "XHSports",
    "cgtnradio",
    "xinhuatravel",
    "flyoverchina",
    "cgtnarabic",
    "MFA_China",
    "Echinanews",
    "HuXijin_GT",
    "CNS1952",
    "shanghaidaily",
    "YZOUTWEETS",
    "zhang_heqing",
    "AmbLiuXiaoMing",
    "AmbQinGang",
    "cgtnamerica",
    "LiuXininBeijing",
    "VisitSuzhou",
    "yicaichina",
    "Guangming_Daily",
    "chenweihua",
    "InQingdao",
    "iChongqing_CIMC",
    "CathayPak",
    "GoJiangsu",
    "CGMeifangZhang",
    "ipandacom",
    "cgtnafrica",
    "Chinamission2un",
    "AmbCuiTiankai",
    "DiscoverNanjing",
    "CaoYi_MFA",
    "CSCECNEWS",
    "VisitSanya",
    "EmbaixadaChina",
    "thouse_opinions",
    "ChineseEmbinUS",
    "China2ASEAN",
    "ChnEmbassy_jp",
    "XisMoments",
    "libijian2",
    "XHscitech",
    "China_Amb_India",
    "BeijingReview",
    "shen_shiwei",
    "izhejiang",
    "BeautyJiangxi",
    "cgtnrussian",
    "AndyBxxx",
    "CRI_Turkish",  # 404
    "AmbChenWeiqing",
    "thisisGBA",
    "WanmingYang",
    "ShaanxiMoments",
    "SixthTone",
    "discoverzj",
    "CriFrancais",
    "Huanqiu_com",
    "realGuancha",
    "PRCAmbNepal",
    "SanyaofChina",
    "xuejianosaka",
    "FuzhouCity",
    "ChinaAmbUN",
    "XuZeyu_Philip",
    "AmbassadeChine",
    "ChineseEmbtoYEM",
    "EmbChinaMex",
    "AmbNong",
    "China__Focus",
    "WuxiCity",
    "MahuiChina",
    "XHJapanese",
    "chinascio",
    "Gwadar_Pro",
    "XIEYongjun_CHN",
    "ChinaAmbSA",
    "InsightNingbo",
    "DXinjiang",
    "Guilin__China",
    "DostiFM98",
    "iloveguizhou",
    "guyanmuchan001",
    "AmbCina",
    "ShaoxingCity",
    "li_xiaosi",
    "RenKeNews",
    "ChineseEmbinUK",
    "PhoenixTV_News",
    "CNContentCenter",
    "PatrickZhengCHN",
    "Li_Yang_China",
    "Amb_LuKang",
    "martinaglobal",
    "chinadotcom_JP",
    "cidcaofficial",
    "SceneryofChina",
    "CCTV_Plus",
    "XHNorthAmerica",
    "takungwenwei_hk",
    "WuPeng_MFAChina",
    "ShanghaiEye",
    "Jingjing_Li",
    "IXiangshan",
    "back_XiaoDiDi",
    "JilinChina",
    "ZichenWanghere",
    "YoloOliver1",
    "Frontlinestory",  # 404
    "ChinaEmbKabul",
    "ChinaEmbEsp",
    "ChineseEmbinRus",
    "EmbZhangRun",
    "ChinaDailyAsia",
    "AmbChangHua",
    "wangxh65",
    "ChinaEUMission",
    "ChinaEmbSL",
    "ZhaLiyou",
    "EmbajadaChinaSV",
    "Chinacultureorg",
    "ExploreGansu",
    "chinafrance",
    "liupheonix",
    "CRIjpn",
    "thepapercn",
    "BeijingDiscover",
    "WangGuanBeijing",  # 404
    "criarabic",
    "ChnConsul_osaka",
    "theserenadong",
    "Amb_Yiming",
    "China_Amb_Mdv",
    "YDunhai",
    "AmbXieFeng",
    "iChangzhou",
    "weiasecas",
    "Amb_ZhuJing",
    "CGTNEurope",
    "AmbCHINEenRDC",
    "ChinaEmbAddis",
    "ChineseZimbabwe",
    "Zhou_Li_CHN",
    "in_embassy",
    "ChinaEmbKSA",
    "Cao_Li_CHN",
    "XHChineNouvelle",
    "AmbLiaoLiqiang",
    "China_Amb_Zim",
    "ZhengguanNews",
    "ChineseEmbKenya",
    "ChineseEmbTZ",
    "GuanchaNewMedia",
    "ChinaEmbAlgeria",
    "ChinaEmbOttawa",
    "oujianhong",
    "muyi_dima",
    "Where_Zhengzhou",
    "Chinaembmanila",
    "haiwaiwangUS",
    "AmbLiuQuan",
    "qingqingparis",
    "PDOAUS",
    "ChinaIraq",
    "FuCong17",
    "AmbChenBo",
    "china_xiamen",
    "ChinaSpox_India",
    "GlobalTimesBiz",
    "WenwenWang1127",
    "ChinainLebanon",
    "Amb_ChenXu",
    "VisitShandong",
    "CGTNGlobalBiz",
    "XinhuaMyanmar",
    "Amazing_Yunnan",
    "xinjiangchannel",
    "ChineseSomalia",
    "kimnaying",
    "ChinaEmbPeru",
    "Tong_Shuo",
    "hongfenghuang",
    "LinHao_BKK",
    "Ambassador_Liu",
    "CHINA_DIPLOMAT",
    "ChineseEmb_Uga",
    "DiscoverGuangxi",
    "eugenioT14",
    "ChenMingjian_CN",
    "ChinaDailyEU",
    "WangXianfeng8",
    "ChinaEmbArg",
    "ChinaAmbBelgium",
    "WangJianPaco",
    "chinaconsulist",
    "zhu_jingyang",
    "SpokespersonHZM",
    "ChinaConSydney",
    "SuzhouWuzhong",
    "AmbDongXiaojun",
    "CGChinaInZurich",
    "china_embajada",
    "Li_Baorong",
    "closertochina",
    "YXiusheng",
    "MAKSIMYQY",
    "AmbZhengZeguang",
    "ChenPingMFA",
    "EmbajadaChinaEc",
    "ChinaEmbajadaRD",
    "MOFCOM_China",
    "ChinaEmbGermany",
    "ChinaEmbinCH",
    "juliojiangwei",
    "LiyingZHU1",
    "CGTNSportsScene",
    "CGHuangPingNY",
    "ZhongBai2020",
    "CCGBelfast",
    "QiushiJournal",
    "ChinaPlusPods",
    "salahzhang",
    "CGZhangPingLA",
    "AmbJiaGuide",
    "ChinaEmbPoland",
    "chinaembaustria",
    "HeRulong",
    "mundo_china",
    "AmbZhouJian",
    "ChinaEmbGrenada",
    "MiaoXiaojuan",
    "fayhaaChina",
    "PRC_Amb_Uganda",
    "EDNewsChina",
    "TideNewsZJ",
    "ChineseLiberia",
    "ChineseEmbinHU",
    "SpoxCHNinUS",
    "tianwei",
    "ChineseEmb_PNG",
    "dotdotnews111",
    "sun_weide",
    "RadioEjani",
    "CHNembinSudan",
    "TibetTodayCN",
    "SichuanDaily",
    "Amb_LiSong",
    "yangliuxh",
    "ChinaEmbEritrea",
    "ChinaEmbNL",
    "ChinaConsulate",
    "TongMediaHK",
    "AmbLiuGuangYuan",
    "chine_guinee",
    "ambchinetchad",
    "ChinaEmbSVK",
    "ChinaEmbinGH",
    "chinaandsamoa",
    "ChineseembassyJ",
    "ChinaMissionGva",
    "promisingzhuang",
    "ChinaEmbIreland",
    "ACSF1919",
    "discoverbinhai",
    "ChinaEmSlovenia",
    "WangJialei4",
    "EmbChinaCuba",
    "PRCAmbNL",
    "Chine_au_Mali",
    "embajadorcn_uy",
    "EmbChinaGE",
    "AmbChineBurundi",
    "EmbChina_RS",
    "AmbWuJianghao",
    "ConsulChinaBcn",
    "PDChinaHK",
    "DrZhaoyongchen",
    "china_emb_ng",
    "ChinaConsAlmaty",
    "PeoplesDailyapp",
    "ConsulateSan",
    "ChinaEmbAngola",
    "CGPRCinDubai",
    "Chinaemb_Hellas",
    "zhaobaogang2011",
    "YayingRUAN",
    "jtao98",
    "ChinaEmbassy_MW",
    "CDHKedition",
    "ChinaCGCalgary",
    "ChinaEmbKuwait",
    "DiscoverJilin",
    "AmbKongXuanyou",
    "ChinaembassyT",
    "reporterCHN",
    "ooeieiwyy",
    "Spacewenchang",
    "CDAfricaNews",
    "ChineAmbMaroc",
    "Hakimyu2",
    "ChnConsulateNgo",
    "GuanXinTweets",
    "chinacgedi",
    "AnnaGE_",
    "GtOpinion",
    "CCGJeddah",
    "ChineseEmb_FJ",
    "ChineAmbDjibout",
    "chinaembcongobz",
    "QuanQuan_1231",
    "AmbChineCmr",
    "ChnConsulateNgt",
    "ChinaEmbKazakh",
    "machinpl",
    "CHN_EGY",
    "yawenxu17",
    "JessicaZ1018",
    "ChinaCG_NYC",
    "beltroadnews",
    "ChinaCG_Muc",
    "ChinaEmbinMR",
    "ChnConsulateFuk",
    "China24Official",
    "WorldInsight_TW",
    "ChinaCG_Ffm",
    "ChinaAmbNL",
    "ChinaEmbPt",
    "ChineseCon_Mel",
    "GlobalWatchCGTN",
    "stuartyueh",
    "peijin_zhang",
    "China_Lyon",
    "ChinaEmbassy_MV",
    "FukLyuGuijun",
    "EmbChinaPa",
    "AlexYsalex17",
    "Hongchencuxian",
    "JiangJiang43",
    "XinhuanetNews",
    "China_OPCW",
    "DrZhaoYanbo",
    "RitaBai",
    "PRCSpoxNepal",
    "ChinaCG_CC",
    "PenicilinPan",
    "shao_zheng",
    "LiuHongyang4",
    "AmbassadorHuang",
    "embassy_chinese",
    "_cultureexpress",
    "ChinaEmbajada",
    "ConsulChinaRJ",
    "consulat_de",
    "wulei2020",
    "zhanhao668",
    "LiuXin_Emily",
    "Henan_TV",
    "liuboleo2",
    "dupingCHN",
    "Lin_Nan1",
    "ChinaEmbMalta",
    "ChinaEmbinRW",
    "jejuZLG",
    "luisxu9",
    "panda_paws",
    "cinitalia",
    "ChinainVan",
    "YaoFei9",
    "ChinaInDenmark",
    "ModernExpressEN",
    "EmbQiMei",
    "TakungNews",
    "yiwen_zh",
    "HU_Bin_CHN",
    "Chen1126",
    "qianwen_gu",
    "Zhang_Xi77",
    "GlobalTimesLife",
    "visitchongqing",
    "ChinaEmbNamibia",
    "ChineseCGMumbai",
    "AmbFangQiu",
    "afghanchina",
    "ChinaEmbAntigua",
    "ChnMission",
    "huanxinzhao",
    "gabriekestabem",
    "CGTNEuropebreak",
    "VicaLi18",
    "_bubblyabby_",
    "CGTNStories",
    "ChinaEmbCroatia",
    "ChineseAmb_GM",
    "GeneralkonsulDu",
    "JingFeng22",
    "YidingYang_MFA",
    "CGTN_Culture",
    "ChineseEmbinMNE",
    "ChinaEmbBahrain",
    "ChineAmbassade",
    "AmbassadorLei",
    "Dr_ZhaoQinghua",
    "ChineseEstonia",
    "ChinaDailyWorld",
    "ChinaDaily_EU",
    "BeijingChannel",
    "haiwainet",
    "cctvxinwen",
    "HunanTimes",
    "ChnConsulateJhb",
    "zhangbuxin",
    "ChinaEmb_Juba",
    "CRIHausaRadio",
    "CHNEmbSuriname",
    "ChinaEmBE",
    "RibiaoChen",
    "ChinaEmbLesotho",
    "SuYuting8",
    "CGTNTech",
    "WuGang_CX",
    "FullFrameCGTN",
    "CGTNBusiness",
    "Yunfei_Zh",
    "cjxwh_hbtv",
    "ChinaEmbInNZ",
    "FangYi85320692",
    "thelinkoncgtn",
    "CGTNSports",
    "EmbChinaVen",
    "CGTN_Dialogue",
    "SXiaochuan258",
    "CD_visual",
    "ChinaCGMTL",
    "ChinaDaily_Life",
    "ChnConsulateNag",
    "CocoStudio4",
    "chineseembassy1",
    "cgtntravelogue",
    "WANG_XUE_JING",
    "ZhongShi_CGTN",
    "kooricuc",
    "CGTNGraphics",
    "wuji_li",
    "chloezhou21",
    "China_Ukraine_",
    "Shanhui_Jacky",
    "bjd_review",
    "MissWow66",
    "yang_zhiyu1979",
    "assignasia",
    "chenhuixin",
    "XuLi52940770",
    "LiuChan14790671",
    "CdOpinion",
    "DIOC_MFA_China",
    "luowill1978",
    "YangZha42341102",
    "xgx91",
    "WeiHongtian",
    "katekuibeijing",
    "xinhua_africa",
    "Chenjuan",
    "bycongwang",
    "huang_jiyuan",
    "xinranz98",
    "CoChwila",
    "CDchinawatch",
    "LiuYanCHN",
    "ZhifeiShen",
    "yicaiglobalCN",
    "SMGKankanews",
    "CGTNTravel",
    "chinatoday_com",
    "evawcheng",
    "CGTNDCproducers",
    "CRIbrk",
    "MediaUnlock",
    "PandaoramaLink",
    "ZhengJunfeng1",
    "ZhaoYing_CRI",
    "thepoint_CGTN",
    "lena90830",
    "learnchineese",
    "WQHChina",
    "ZShilei",
    "ziyi_zeng",
    "MMMKKK56665147",
    "Dongning",
    "HongtieZhang",
    "MingjieReporter",
    "JianhuaLi4",
    "LYNNJie3",
    "lingzhi_van",
    "Yikangmama",
    "Todayreview_hk",
    "WaveMedia2022",
    "heweiwei_",
    "CenJasmine",
    "dier0806",
    "CHENWendi11",
    "crigreek",
    "Bossebosse84",
    "anosiwang",
    "pd_northamerica",
    "YichuSong",
    "dragontv",
    "LiuYutongpost",
    "mingalanews",
    "CDscitech",
    "ChinaYouthOL",
    "CRIsinhala",
    "idiscoverchina",
    "suadye",
    "UnTeresa",
    "prcembassyprg",
    "ZoomIn_CGTN",
    "KunkunkunLiu",
    "are_china",
    "hui48298914",
    "CGTNFood",
    "EconomicMalawi",
    "ayishaelseenya",
    "IN_Studio2020",
    "criurdu",
    "CGTNMovies",
    "ShannonZ666",
    "amysaina",
    "feelchina2021",
    "MarthayTao",
    "DingHeng6",
    "aMEDIAchallenge",
    "Sabrina_Zhao",
    "cripashto",
    "mmMonicaZhang",
    "CGTN_Style",
    "tianranhe",
    "CRIGerman1",
    "cri_hindi",
    "SWAHILICRI",
    "gz1988",
    "theChinaMosaic",
    "cgtnun",
    "yangrui88",
    "Yuanjia33107056",
    "Leona_BJ",
    "Danni_Zhu131",
    "gabrielyin",
    "KatieMi17",
    "xinhuasylvia",
    "GladysGuo",
    "shenqihaodianzi",
    "Shalevetyah",
    "BlairZheng1",
    "wty510",
    "MelodyZ77141898",
    "yuqiaoji",
    "lovejiaxing",
    "cgtn_inheritors",
    "delkhiintsag",
]

url = 'https://twitter.com/i/api/graphql/G3KGOASz96M-Qu0nwmGXNg/UserByScreenName'
headers = {
    'authority': 'twitter.com',
    'accept': '*/*',
    'accept-language': 'en-US,en;q=0.9',
    'authorization': 'Bearer ***REMOVED***',
    'content-type': 'application/json',
    'cookie': '_ga=GA1.2.1516747026.1700257313; _gid=GA1.2.384391922.1700257313; guest_id=v1%3A170025731328715985; _twitter_sess=BAh7CSIKZmxhc2hJQzonQWN0aW9uQ29udHJvbGxlcjo6Rmxhc2g6OkZsYXNo%250ASGFzaHsABjoKQHVzZWR7ADoPY3JlYXRlZF9hdGwrCGW7O9%252BLAToMY3NyZl9p%250AZCIlMDgwMmFjMTU0ZmJjNDJiM2Y5ZTcwNjYyZDMzYjdhY2E6B2lkIiVkY2Qy%250AYmUxM2JkMDMxODU4YzZlODk3Y2RiZmRlMTAwMw%253D%253D--5f2904f6c9f2d0a1b3f164574c9061c6eb913821; kdt=IvRhczUxIttZZxeD91D1kMq3g3eBZkSAYgRGgaD7; auth_token=ae3fcf71d1d450cc2bcd271eea70b0140c024cb6; ct0=a6c4ad6ac22cdafb75c9b5165389533f59a6b0bbe8a4648859036e38eecd108076e15b4b476a8167de9516f0974a95d6e31d436084f790b471b16592d6827a98c6546f7b2b1465d6677eab26eb25d0ed; att=1-KZ219hVs1tUWvfDG6d41QU5YJq7DuU8L6uGgXAPc; guest_id_ads=v1%3A170025731328715985; guest_id_marketing=v1%3A170025731328715985; lang=en; twid=u%3D767620711414456320; personalization_id="v1_NiRxj5bQIG4W+c6MBQ587A=="',
    'referer': 'https://twitter.com/_bubblyabby_',
    'sec-ch-ua': '"Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
    'x-client-transaction-id': 'nxYjqv9368nh5726ylPaAnQ9IczOUf5SQfR0wUYLxdANK9VZnx0SselcFToHUJ43TiEWl54QC/5aH0LznOx5hPFsbdUGng',
    'x-client-uuid': '089d796a-50ee-4e30-a9ee-e06452004b4c',
    'x-csrf-token': 'a6c4ad6ac22cdafb75c9b5165389533f59a6b0bbe8a4648859036e38eecd108076e15b4b476a8167de9516f0974a95d6e31d436084f790b471b16592d6827a98c6546f7b2b1465d6677eab26eb25d0ed',
    'x-twitter-active-user': 'yes',
    'x-twitter-auth-type': 'OAuth2Session',
    'x-twitter-client-language': 'en',
}

# Variables and payload
variables = {
    "screen_name": "_bubblyabby_",
    "withSafetyModeUserFields": True
}
features = {
    "hidden_profile_likes_enabled": True,
    "hidden_profile_subscriptions_enabled": True,
    "responsive_web_graphql_exclude_directive_enabled": True,
    "verified_phone_label_enabled": False,
    "subscriptions_verification_info_is_identity_verified_enabled": True,
    "subscriptions_verification_info_verified_since_enabled": True,
    "highlights_tweets_tab_ui_enabled": True,
    "creator_subscriptions_tweet_preview_api_enabled": True,
    "responsive_web_graphql_skip_user_profile_image_extensions_enabled": False,
    "responsive_web_graphql_timeline_navigation_enabled": True
}
field_toggles = {
    "withAuxiliaryUserLabels": False
}

rest_map = {}

for index, user in enumerate(users[156:]):
    variables["screen_name"] = user
    payload = {
        "variables": json.dumps(variables),
        "features": json.dumps(features),
        "fieldToggles": json.dumps(field_toggles)
    }

    print(f"{index + 1 + 156}/{len(users)} Crawling for {user}")
    try:
        response = requests.get(url, headers=headers, params=payload)
        data = response.json()
        rest_map[user] = data["data"]["user"]["result"]["rest_id"]

        f = open(f"users/{user}.json", "w")
        f.write(json.dumps(data))
        f.flush()
        f.close()
    except Exception as ex:
        print("\tfailed to fetch")

    time.sleep(2)

print("---------------------------------------------------")
print(rest_map)
